defaults: &defaults
  config:
    address: smtp.163.com
    port: 25,
    user_name: zhangcaiyanbeyond@163.com
    password: zcy142322
    authentication: :login
    domain: 163.com 



development:
  <<: *defaults
  host:
    host: localhost:3000 

test:
  <<: *defaults

production:
  <<: *defaults
  host:
    host: www.wode521.com
