defaults: &defaults
  user:
    email: zhangcaiyanbeyond@gmail.com 
    username: zhangcaiyan
    password: zhangcaiyan
    password_confirmation: zhangcaiyan


  test:
    email: <%= Faker::Internet.email %>
    username: <%= Faker::Name.name %>
    password: zhangcaiyan
    password_confirmation: zhangcaiyan

    

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
